### ISSUE TITLE
src-data?

### ISSUE THREAD

**Issue by solsend2l** [MahdiF/loud-links#1]
Pretty sure the README should actually say:

`<div class=“loud-link-hover” data-src=“sound”></div>`

**Comment by MahdiF** [comment]
Oops! Yeah you're right, just fixed it. Thanks Steven.

**Comment by solsend2l** [comment]
yw! 

(I hope devs use this lib responsibility :wink:)

**Comment by MahdiF** [comment]
I hope so as well, specially game devs/designers.

Thanks again 👍
