### ISSUE TITLE
Is there any way to prevent hover audio to replay until it's finished?

### ISSUE THREAD

**Issue by fernandofleury** [MahdiF/loud-links#11]
Maybe provide an `data-` to prevent the sound from stopping on `mouseleave`? Stop/play on multiple hover effects gets a bit odd.

**Comment by MahdiF** [comment]
You can do that yourself by removing it from the code. I think it's better to let it Stop/Play when hovering a new element so it plays the new sound instantly without waiting the previous one to finish playing, as it might be annoying to hear multiple sounds at the same time.
