### ISSUE TITLE
Simple Jsfiddle example not working

### ISSUE THREAD

**Issue by mburakerman** [MahdiF/loud-links#13]
I just saw your plugin and tried to make a simple demo for myself but not working.

I used your plugin as cdn ' https://cdn.rawgit.com/MahdiF/loud-links/master/loudlinks.js '
and then just added 
 `<div class=“loud-link-hover” data-sound="http://sifidesign.com/audio/explosion.mp3"> Hover me </div>` to my html.

Why this is not working ?

[**JSFIDDLE**](https://jsfiddle.net/6xuts8jx/)

**Comment by MahdiF** [comment]
Check https://jsfiddle.net/4rnp3ceL/

in `class=“loud-link-hover”` you were using the wrong quotations, I just
changed it to `class='loud-link-hover'`

Also for  the file extension, you should use `{{type}}` instead of the `.mp3`
